name: Deploy to EC2 (Amazon Linux)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    # Use your self-hosted runner running on Amazon Linux
    runs-on: self-hosted

    steps:
      # 1️⃣ Pull latest commit
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2️⃣ Setup Node.js (for Amazon Linux)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Ensure PM2 is installed globally
      - name: Ensure PM2 globally installed
        run: |
          if ! command -v pm2 >/dev/null 2>&1; then
            echo "Installing PM2 globally..."
            sudo npm install -g pm2
          else
            echo "PM2 already installed."
          fi
          pm2 -v

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci || npm install

      # 5️⃣ Optional Build Step
      - name: Build project (optional)
        run: |
          if [ -f package.json ] && grep -q "\"build\"" package.json; then
            echo "Running build..."
            npm run build
          else
            echo "No build script found, skipping."
          fi

      # 6️⃣ Start / Reload app with PM2 using npm run dev
      - name: Start app with PM2 (npm run dev)
        run: |
          APP_NAME="247B"
          if pm2 list | grep -q "$APP_NAME"; then
            echo "Reloading existing PM2 process..."
            pm2 reload "$APP_NAME" --update-env
          else
            echo "Starting new PM2 process..."
            pm2 start npm --name "$APP_NAME" -- run dev
          fi

          # Enable PM2 startup for Amazon Linux systemd
          pm2 startup systemd -u ec2-user --hp /home/ec2-user || true
          pm2 save
          pm2 status
