name: Deploy to EC2 (Self-hosted)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Pull latest commit
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Ensure PM2 is installed (only if not already)
      - name: Ensure PM2 globally installed
        run: |
          if ! command -v pm2 >/dev/null 2>&1; then
            echo "Installing PM2 globally..."
            npm install -g pm2
          else
            echo "PM2 already installed."
          fi
          pm2 -v

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci || npm install

      # 5️⃣ Build step (skip if no build script)
      - name: Build project
        run: |
          if [ -f package.json ] && grep -q "\"build\"" package.json; then
            npm run build
          else
            echo "No build script found, skipping build."
          fi

      # 6️⃣ Start / Reload app with PM2 using npm run dev
      - name: Start app with PM2 (npm run dev)
        run: |
          APP_NAME="247B"
          if pm2 list | grep -q "$APP_NAME"; then
            echo "Reloading existing PM2 process..."
            pm2 reload "$APP_NAME" --update-env
          else
            echo "Starting new PM2 process..."
            pm2 start npm --name "$APP_NAME" -- run dev
          fi
          pm2 save
          pm2 status
