name: Deploy to EC2 (Self-hosted)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Pull latest code
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1   # just latest commit
          token: ${{ secrets.GITHUB_TOKEN }}  # built-in token, no PAT needed

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci || npm install

      # 4️⃣ Build (skip if no build script)
      - name: Build project
        run: |
          if [ -f package.json ] && grep -q "\"build\"" package.json; then
            npm run build
          else
            echo "No build script found, skipping build."
          fi

      # 5️⃣ Start / Reload app with PM2
      - name: Start app with PM2
        run: |
          APP_NAME="247B"
          if ! command -v pm2 >/dev/null 2>&1; then
            npm install -g pm2
          fi
          if pm2 list | grep -q "$APP_NAME"; then
            pm2 reload "$APP_NAME" --update-env
          else
            pm2 start npm --name "$APP_NAME" -- run start
          fi
          pm2 save
          pm2 status
